spring:
  application:
    name: SmartFridgeAi

  datasource:
    url: jdbc:mysql://localhost:3306/tripplannerai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-plataform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  flyway:
    enabled: true

gemini:
  api:
    url: https://generativelanguage.googleapis.com
    key: ${KEY_GEMINI}